### ISSUE TITLE
Connection Diagram for DMD + Raspi

### ISSUE THREAD

**Issue by beniroquai** [openSIMMO/openSIMMO.github.io#25]
@ranranking I remember seeing a little diagram on your screen that showed the flowchart of raspi, imswitch and camera. Should we add this here? 
https://opensimmo.github.io/docs/Electronics

**Comment by ranranking** [comment]
yeap, should we add it now or after the paper

**Comment by beniroquai** [comment]
Now is fine in my opinion :)

**Comment by ranranking** [comment]
i pushed it here https://github.com/openSIMMO/openSIMMO.github.io/blob/main/docs/IMAGES/SIMMO_Hardware.pdf
